programming_words = [
    'Abstraction', # beginner
    'Active Record',
    'Agile',
    'Agile Software Development',
    'AJAX',
    'Algorithms',
    'Algorithm' # advanced
    'Angular.js', # advanced
    'Apache',
    'API', #
    'Apprenticeship',
    'Argument', #
    'Arithmetic Operators', #
    'Array', #
    'ASCII',
    'Assignment Operators',
    'Asynchronous Learning',
    'Asynchronous Programming Languages',
    'Augmented Reality',
    'Autonomous', #
    'Automation', #
    'Back End', #
    'Backbone.js',
    'Binary',
    'Binary Alphabet',
    'Binary Numbers',
    'Bit',
    'Block-based Programming Language',
    'Blockly',
    'Boolean', #
    'Bootstrap', #
    'Bug',#
    'Build',
    'Byte',
    'Binary Trees',#
    'C plus plus',
    'Call a function',#
    'Call a variable',#
    'Camel Case',#
    'Char',
    'Class',#
    'Click',
    'Cloud',
    'Code',
    'Code Review',
    'Coding',
    'Coding Challenge',
    'Coding Languages',
    'Command',
    'Command-line',
    'Command-line Interface',
    'Compilation',
    'Compiler',
    'Computational Thinking',
    'Computer Program',
    'Computer Science',
    'Conditional Statements',
    'Constants',
    'Crowdsourcing',
    'CSS',
    'Cybersecurity',
    'C',
    'C#',
    'C sharp'
    'Data',
    'Data Science',
    'Data Structures',
    'Data Types',
    'Database',
    'Database models'
    'Debugging',
    'Declaration',
    'Decompose',
    'Define a function',
    'Deployment',
    'Digital Footprint',
    'Django',
    'Jango',
    'DNS',
    'domain name service',
    'Double-click',
    'Drag',
    'Drop',
    'DRY',
    'DSL/Cable',
    'Else Statements',
    'Endless Loop',
    'Event',
    'Event Handler',
    'Exception',
    'Express.js',
    'Expression',
    'F.A.I.L.',
    'Flask',
    'For Loop',
    'Framework',
    'Front End',
    'Full Stack Developer',
    'Function',
    'Function Call',
    'Function Definition',
    'Git',
    'Github',
    'HAML',
    'Hardcode',
    'High-level Language',
    'HTML',
    'HTTP Request',
    'IDE',
    'Integrated Development Environment',
    'If Statement',
    'Inheritance',
    'Input',
    'IntelliJ',
    'Internet',
    'IOS Swift',
    'Swift',
    'IP Address',
    'Iteration',
    'Java',
    'JavaScript',
    'JavaScript Framework',
    'jQuery',
    'JSON',
    'JavaScript Object Notation',
    'Junior Developer',
    'Keywords',
    'LAMP Stack',
    'Linter',
    'Linux',
    'Linked Lists',
    'Local Environment',
    'Loop',
    'Lua',
    'Low-level Language',
    'Machine Language',
    'Machine Learning',
    'Main Function',
    'Markup Language',
    'MEAN Stack',
    'Micro:bit',
    'MongoDB',
    'MVC',
    'MySQL',
    'Neural Networks',
    'Nodes',
    'Node.js',
    'Null',
    'Object Oriented Programming',
    'OOP',
    'Object Related Database Management System',
    'ORDBMS',
    'Objects',
    'Online',
    'Open-Source Software Development',
    'Operand',
    'Operator',
    'OS',
    'Operating System',
    'Output',
    'Package',
    'Packets',
    'Pair Programming',
    'Parameter',
    'Pattern Matching',
    'Persistence',
    'PHP',
    'Pixel',
    'Pointer',
    'Postgresql',
    'Program',
    'Programming',
    'Programming Language',
    'Programming Languages'
    'Project based Learning',
    'Python',
    'R',
    'React',
    'React Native',
    'Relational Database Management System',
    'RDBMS',
    'Repeat',
    'REST',
    'RESTful',
    'Ruby',
    'Ruby on Rails',
    'Run Program',
    'Runtime',
    'SASS',
    'Scratch',
    'Scripting Language',
    'Scripts',
    'Search Engine',
    'Server',
    'Server-side',
    'Source Code',
    'Source Data',
    'Sprint',
    'Sprites',
    'SQL',
    'Structured Query Language',
    'Stack',
    'Statement',
    'Synchronous Learning',
    'Syntax',
    'Teaching Language',
    'Tensor Flow',
    'Tensorflow',
    'Terminal',
    'Token',
    'Training',
    'Typescript'
    'URL',
    'Usability Testing',
    'User Experience Design',
    'UX Design',
    'User Interface Design',
    'UI Design',
    'Username',
    'Variable',
    'Variable Types',
    'Version Control',
    'Website',
    'While Loop',
    'Whiteboarding',
    'Wi-Fi',
    'Xcode',
    'XML',
]

beginner = [
    'Arithmetic Operators',
    'Array',
    'Assignment Operators',
    'Arguement',
    'Boolean',
    'Bug',
    'Call a function',
    'Call a variable',
    'Camel Case',
]

intermediate = [
    'Abstraction',
    'Back End',
    'Bootstrap',
    'Binary Trees',
    'Class',
    'classes',

]

advanced = [
    'Algorithms',
    'Algorithm',
    'API',
    'Automation',
    'Autonomous'

]

languages = [
    'C',
    'C plus plus',
    'C sharp',
    'C#'
    'CSS',
    'HTML',
    'IOS Swift',
    'Swift',
    'Java',
    'Javascript',
    'Python',
    'PHP',
    'R',
    'Ruby',
    'Ruby On Rails',
    'SASS',
    'Scratch',
    'Sprint',
    'Typescript',
]

general_words = [

]
